// Writes src/palettes.ts: palettes built from the template's OKLCH lightness and chroma per role, shaped by `shape`, with new hues.
import { writeFileSync } from "node:fs";

const template = { ink: "#dbfe87", paper: "#394053", stone: "#4e4a59", "line-dark": "#6e6362", accent: "#7cae7a", lily: "#839073" };
/** Per role: [lightness shift, chroma multiplier] applied to the template. */
const shape: Record<string, [number, number]> = {
  ink: [0, 1.2],
  paper: [-0.06, 2.6],
  stone: [-0.05, 2.6],
  "line-dark": [-0.03, 3],
  accent: [0, 1.5],
  lily: [-0.02, 2.2],
};
const COUNT = 20;
const L_BAND = 0.03;
const HUE_JITTER = 75;
/** Ink gives up lightness, down to INK_MIN_L, until it can hold this much chroma. */
const INK_CHROMA = 0.13;
const INK_MIN_L = 0.84;

type Lch = [number, number, number];

const toLinear = (c: number) => (c <= 0.04045 ? c / 12.92 : ((c + 0.055) / 1.055) ** 2.4);
const toGamma = (c: number) => (c <= 0.0031308 ? 12.92 * c : 1.055 * c ** (1 / 2.4) - 0.055);

const hexToRgb = (hex: string) => [1, 3, 5].map((i) => toLinear(parseInt(hex.slice(i, i + 2), 16) / 255));

const toOklch = (hex: string): Lch => {
  const [r, g, b] = hexToRgb(hex);
  const l = Math.cbrt(0.4122214708 * r + 0.5363325363 * g + 0.0514459929 * b);
  const m = Math.cbrt(0.2119034982 * r + 0.6806995451 * g + 0.1073969566 * b);
  const s = Math.cbrt(0.0883024619 * r + 0.2817188376 * g + 0.6299787005 * b);
  const a = 1.9779984951 * l - 2.428592205 * m + 0.4505937099 * s;
  const B = 0.0259040371 * l + 0.7827717662 * m - 0.808675766 * s;
  return [0.2104542553 * l + 0.793617785 * m - 0.0040720468 * s, Math.hypot(a, B), (Math.atan2(B, a) * 180) / Math.PI];
};

/** Linear sRGB, possibly outside [0, 1]. */
const fromOklch = ([L, C, h]: Lch) => {
  const a = C * Math.cos((h * Math.PI) / 180);
  const b = C * Math.sin((h * Math.PI) / 180);
  const l = (L + 0.3963377774 * a + 0.2158037573 * b) ** 3;
  const m = (L - 0.1055613458 * a - 0.0638541728 * b) ** 3;
  const s = (L - 0.0894841775 * a - 1.291485548 * b) ** 3;
  return [
    4.0767416621 * l - 3.3077115913 * m + 0.2309699292 * s,
    -1.2684380046 * l + 2.6097574011 * m - 0.3413193965 * s,
    -0.0041960863 * l - 0.7034186147 * m + 1.707614701 * s,
  ];
};

const inGamut = (rgb: number[]) => rgb.every((c) => c >= -1e-4 && c <= 1 + 1e-4);

/** Largest chroma at this lightness and hue that fits sRGB. */
const maxChroma = (L: number, h: number) => {
  let lo = 0;
  let hi = 0.4;
  for (let i = 0; i < 20; i++) inGamut(fromOklch([L, (lo + hi) / 2, h])) ? (lo = (lo + hi) / 2) : (hi = (lo + hi) / 2);
  return lo;
};

/** Lowers chroma at fixed lightness and hue until the colour fits sRGB. */
const toHex = ([L, C, h]: Lch) => {
  const hex = `#${fromOklch([L, Math.min(C, maxChroma(L, h)), h])
    .map((c) => Math.round(Math.min(1, Math.max(0, toGamma(c))) * 255).toString(16).padStart(2, "0"))
    .join("")}`;
  const got = toOklch(hex)[0];
  if (Math.abs(got - L) > 0.01) throw new Error(`${hex} has lightness ${got.toFixed(3)}, asked for ${L.toFixed(3)}`);
  return hex;
};

const inkLightness = (L: number, h: number) => {
  while (L > INK_MIN_L && maxChroma(L, h) < INK_CHROMA) L -= 0.01;
  return L;
};

const luminance = (hex: string) => {
  const [r, g, b] = hexToRgb(hex);
  return 0.2126 * r + 0.7152 * g + 0.0722 * b;
};
const contrast = (x: string, y: string) => {
  const [hi, lo] = [luminance(x), luminance(y)].sort((p, q) => q - p);
  return (hi + 0.05) / (lo + 0.05);
};

// mulberry32, seeded so a rerun writes the same file
let seed = 1;
const random = () => {
  seed = (seed + 0x6d2b79f5) | 0;
  let t = Math.imul(seed ^ (seed >>> 15), seed | 1);
  t ^= t + Math.imul(t ^ (t >>> 7), t | 61);
  return ((t ^ (t >>> 14)) >>> 0) / 4294967296;
};
const jitter = (n: number) => (random() * 2 - 1) * n;

const roles = Object.entries(template).map(([name, hex]) => [name, toOklch(hex)] as const);

const palettes = [template as Record<string, string>];
for (let i = 1; i < COUNT; i++) {
  const shift = (i * 360) / COUNT + jitter(360 / COUNT / 2);
  palettes.push(
    Object.fromEntries(
      roles.map(([name, [L, C, h]]) => {
        const [dL, cScale] = shape[name];
        const hue = h + shift + (name === "ink" ? 0 : jitter(HUE_JITTER));
        const lightness = name === "ink" ? inkLightness(L, hue) : L + dL + jitter(L_BAND);
        return [name, toHex([lightness, C * cScale * (1 + jitter(0.15)), hue])];
      }),
    ),
  );
}

for (const p of palettes) {
  if (contrast(p.ink, p.paper) < 7) throw new Error(`ink ${p.ink} on paper ${p.paper} is only ${contrast(p.ink, p.paper).toFixed(1)}:1`);
}

const rows = palettes.map((p) => `  { ${Object.entries(p).map(([k, v]) => `${/-/.test(k) ? `"${k}"` : k}: "${v}"`).join(", ")} },`);
writeFileSync(
  new URL("../src/palettes.ts", import.meta.url),
  `// Generated by scripts/palettes.ts (bun run palettes). Entry 0 is the default; delete any you dislike.\nexport const palettes = [\n${rows.join("\n")}\n];\n\nexport type Palette = (typeof palettes)[number];\n`,
);
console.log(`wrote ${palettes.length} palettes`);
