// Generated by scripts/palettes.ts (bun run palettes). Entry 0 is the default; delete any you dislike.
export const palettes = [
  { ink: "#dbfe87", paper: "#394053", stone: "#4e4a59", "line-dark": "#6e6362", accent: "#7cae7a", lily: "#839073" },
  { ink: "#aeffa9", paper: "#3c2b67", stone: "#3d3b65", "line-dark": "#7c5d56", accent: "#31b17f", lily: "#828338" },
  { ink: "#97ffb2", paper: "#461b3c", stone: "#263f61", "line-dark": "#605a41", accent: "#00b6b7", lily: "#8d8d44" },
  { ink: "#53ffe7", paper: "#342d5b", stone: "#50324d", "line-dark": "#785852", accent: "#66ae6e", lily: "#399ba5" },
  { ink: "#42f0ff", paper: "#491840", stone: "#564313", "line-dark": "#486c5e", accent: "#00b184", lily: "#399f8b" },
  { ink: "#64dbff", paper: "#471f55", stone: "#5c3a51", "line-dark": "#5a593e", accent: "#00b5d3", lily: "#2188b0" },
  { ink: "#8ed3ff", paper: "#491643", stone: "#582a2a", "line-dark": "#4d614e", accent: "#00abb8", lily: "#7185bc" },
  { ink: "#9fcfff", paper: "#54213a", stone: "#335028", "line-dark": "#645641", accent: "#d874b4", lily: "#8d6ea7" },
  { ink: "#b8c7ff", paper: "#332e00", stone: "#5c3025", "line-dark": "#576a55", accent: "#ea7da9", lily: "#8c71ae" },
  { ink: "#c0c4ff", paper: "#611e12", stone: "#553323", "line-dark": "#62654a", accent: "#6795f5", lily: "#648dc7" },
  { ink: "#d4bbff", paper: "#442500", stone: "#294d37", "line-dark": "#4a6857", accent: "#58a0ec", lily: "#b66e83" },
  { ink: "#ecafff", paper: "#5d2218", stone: "#2f4a2d", "line-dark": "#526a59", accent: "#e47185", lily: "#8778c3" },
  { ink: "#ffacf5", paper: "#4b2c00", stone: "#1e4829", "line-dark": "#335f60", accent: "#d57e01", lily: "#747cbf" },
  { ink: "#ffaeca", paper: "#00342a", stone: "#1d4561", "line-dark": "#39605d", accent: "#d173b6", lily: "#a96768" },
  { ink: "#ffb0c0", paper: "#003d34", stone: "#004c51", "line-dark": "#416d6d", accent: "#c788df", lily: "#b06d6c" },
  { ink: "#ffb3ac", paper: "#003417", stone: "#004c54", "line-dark": "#605f77", accent: "#e78472", lily: "#a18649" },
  { ink: "#ffb695", paper: "#303b00", stone: "#005151", "line-dark": "#6a556b", accent: "#d28448", lily: "#858e50" },
  { ink: "#ffba64", paper: "#003524", stone: "#004049", "line-dark": "#6c5f7a", accent: "#b89000", lily: "#c26b81" },
  { ink: "#ffca68", paper: "#2f295e", stone: "#1c4561", "line-dark": "#7a5b58", accent: "#75b669", lily: "#be7664" },
  { ink: "#effa55", paper: "#292a56", stone: "#553355", "line-dark": "#604d66", accent: "#00b396", lily: "#4d8c64" },
];

export type Palette = (typeof palettes)[number];
